import type { OrchestrationConfig } from '../core/types';

export function generateExportReadme(
  config: OrchestrationConfig,
  platform: string
): string {
  return `# 🎲 Agents Party: ${config.questName}

This package contains your customized **Agent Orchestration** setup, optimized for **${platform}**.

## 🏗️ The 3-Tier Hierarchy

The system follows a separation of concerns inspired by Dungeons & Dragons:

1.  **The War Room (Meta-Level):** Strategic planning, brainstorming, and high-level rule-setting. This session runs in **this directory** (the orchestration folder).
2.  **The GM Session (Coordinator):** The primary coordinator that manages the quest. This session runs **inside your target codebase**.
3.  **The Party (Sub-Agents):** Specialized workers (Ranger, Wizard, Warrior, etc.) spawned by the GM to execute focused tasks.

## 🚀 Getting Started

### 1. Initialize the War Room
Start your meta-session in this directory to refine the quest goals and rules.
\`\`\`bash
# 1. Ensure scripts are executable
chmod +x start-war-room.sh start-quest.sh

# 2. Launch the War Room
./start-war-room.sh
\`\`\`

### 2. Launch the Quest
Navigate to the root of your **target codebase repository** and run the quest session using the absolute path to the helper script in this folder.
\`\`\`bash
# From inside your project's root directory:
/path/to/this/folder/start-quest.sh .
\`\`\`

## 📂 Folder Structure
- \`war-room.md\`: Instructions for the meta-level planners.
- \`gm-guide.md\` (or \`SKILL.md\`): The coordination manual for the Game Master.
- \`party/\`: The character sheets and specialized prompts for your sub-agents.
- \`journal.md\`: (Generated during quest) The shared log for agent communication.

## 🛠️ Customization

**Important:** If you are using a different AI agent or CLI tool than the one selected during export, you must manually edit the \`start-war-room.sh\` and \`start-quest.sh\` scripts to point to your specific agent command.

Generated by [Agents Party](https://agentsparty.dev)
`;
}
