import type { OrchestrationConfig } from '../core/types';

export function generateExportReadme(
  config: OrchestrationConfig,
  platform: string
): string {
  let experimentalNote = '';
  if (platform === 'Gemini') {
    experimentalNote = `\n### ⚠️ Experimental Features Required
For the **Gemini Subagents** to work natively in parallel, you must enable experimental agent support in your global Gemini CLI settings:
Ensure \`"experimental": { "enableAgents": true }\` is set in your \`settings.json\`.

*Note: The \`start-quest.sh\` script will automatically copy the generated \`.gemini/\` subagent folder into your target codebase and append it to your \`.gitignore\` so the GM session can access them.*
`;
  } else if (platform === 'OpenAI') {
    experimentalNote = `\n### ⚠️ Experimental Features Required
For the **Codex Multi-Agent** orchestrator to work natively, you must have the experimental multi-agent feature enabled (e.g. \`multi_agent = true\` in your config or via \`/experimental\` toggle).

*Note: The \`start-quest.sh\` script will automatically copy the generated \`.codex/\` orchestrator folder into your target codebase and append it to your \`.gitignore\` so the GM session can access them.*
`;
  } else if (platform === 'Claude') {
    experimentalNote = `\n### 💡 Agent Teams
Claude supports "Agent Teams" natively. If you want a highly collaborative, parallelized session instead of standard hub-and-spoke subagents, you can append \`--team\` to the Claude command inside the \`start-quest.sh\` script!
`;
  }

  return `# 🎲 Agents Party: ${config.questName}

This package contains your customized **Agent Orchestration** setup, optimized for **${platform}**.
${experimentalNote}
## 🏗️ The 3-Tier Hierarchy

The system follows a separation of concerns inspired by Dungeons & Dragons:

1.  **The Throne Room (Meta-Level):** Strategic planning, brainstorming, and high-level rule-setting. This session runs in **this directory** (the orchestration folder).
2.  **The GM Session (Coordinator):** The primary coordinator that manages the quest. This session runs **inside your target codebase**.
3.  **The Party (Sub-Agents):** Specialized workers (Ranger, Wizard, Warrior, etc.) spawned by the GM to execute focused tasks.

## 🚀 Getting Started

### 1. Initialize the Throne Room
Start your meta-session in this directory to refine the quest goals and rules.
\`\`\`bash
# 1. Ensure scripts are executable
chmod +x start-throne-room.sh start-quest.sh

# 2. Launch the Throne Room
./start-throne-room.sh
\`\`\`

### 2. Launch the Quest
Navigate to the root of your **target codebase repository** and run the quest session using the absolute path to the helper script in this folder.
\`\`\`bash
# From inside your project's root directory:
/path/to/this/folder/start-quest.sh .
\`\`\`

## 📂 Folder Structure
- \`throne-room/\` (or \`meta/\`): Instructions for the meta-level planners (Game Creator, Bard, Master of Spies).
- \`gm-guide.md\` (or \`SKILL.md\`): The coordination manual for the Game Master.
- \`party/\`: The character sheets and specialized prompts for your sub-agents.
- \`journal.md\`: (Generated during quest) The shared log for agent communication.

## 🛠️ Customization

**Important:** If you are using a different AI agent or CLI tool than the one selected during export, you must manually edit the \`start-throne-room.sh\` and \`start-quest.sh\` scripts to point to your specific agent command.

Generated by [Agents Party](https://agentsparty.dev)
`;
}
